services:
  postgres_drop_points_crawler:
    build: .
    image: postgres_drop-points-crawler
    container_name: postgres-drop-points-crawler
    volumes:
      - ./config.toml:/usr/src/app/config.toml
      - ./store:/usr/src/app/store
    ports:
      - 3000:3000
    entrypoint: [ "bun", "serve" ]
  postgres:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data: