import * as _217 from "./abci/types";
import * as _218 from "./crypto/keys";
import * as _219 from "./crypto/proof";
import * as _220 from "./libs/bits/types";
import * as _221 from "./p2p/types";
import * as _222 from "./types/block";
import * as _223 from "./types/evidence";
import * as _224 from "./types/params";
import * as _225 from "./types/types";
import * as _226 from "./types/validator";
import * as _227 from "./version/types";
export declare namespace tendermint {
    const abci: {
        checkTxTypeFromJSON(object: any): _217.CheckTxType;
        checkTxTypeToJSON(object: _217.CheckTxType): string;
        responseOfferSnapshot_ResultFromJSON(object: any): _217.ResponseOfferSnapshot_Result;
        responseOfferSnapshot_ResultToJSON(object: _217.ResponseOfferSnapshot_Result): string;
        responseApplySnapshotChunk_ResultFromJSON(object: any): _217.ResponseApplySnapshotChunk_Result;
        responseApplySnapshotChunk_ResultToJSON(object: _217.ResponseApplySnapshotChunk_Result): string;
        responseProcessProposal_ProposalStatusFromJSON(object: any): _217.ResponseProcessProposal_ProposalStatus;
        responseProcessProposal_ProposalStatusToJSON(object: _217.ResponseProcessProposal_ProposalStatus): string;
        responseVerifyVoteExtension_VerifyStatusFromJSON(object: any): _217.ResponseVerifyVoteExtension_VerifyStatus;
        responseVerifyVoteExtension_VerifyStatusToJSON(object: _217.ResponseVerifyVoteExtension_VerifyStatus): string;
        misbehaviorTypeFromJSON(object: any): _217.MisbehaviorType;
        misbehaviorTypeToJSON(object: _217.MisbehaviorType): string;
        CheckTxType: typeof _217.CheckTxType;
        CheckTxTypeSDKType: typeof _217.CheckTxType;
        CheckTxTypeAmino: typeof _217.CheckTxType;
        ResponseOfferSnapshot_Result: typeof _217.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultSDKType: typeof _217.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultAmino: typeof _217.ResponseOfferSnapshot_Result;
        ResponseApplySnapshotChunk_Result: typeof _217.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultSDKType: typeof _217.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultAmino: typeof _217.ResponseApplySnapshotChunk_Result;
        ResponseProcessProposal_ProposalStatus: typeof _217.ResponseProcessProposal_ProposalStatus;
        ResponseProcessProposal_ProposalStatusSDKType: typeof _217.ResponseProcessProposal_ProposalStatus;
        ResponseProcessProposal_ProposalStatusAmino: typeof _217.ResponseProcessProposal_ProposalStatus;
        ResponseVerifyVoteExtension_VerifyStatus: typeof _217.ResponseVerifyVoteExtension_VerifyStatus;
        ResponseVerifyVoteExtension_VerifyStatusSDKType: typeof _217.ResponseVerifyVoteExtension_VerifyStatus;
        ResponseVerifyVoteExtension_VerifyStatusAmino: typeof _217.ResponseVerifyVoteExtension_VerifyStatus;
        MisbehaviorType: typeof _217.MisbehaviorType;
        MisbehaviorTypeSDKType: typeof _217.MisbehaviorType;
        MisbehaviorTypeAmino: typeof _217.MisbehaviorType;
        Request: {
            typeUrl: string;
            encode(message: _217.Request, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.Request;
            fromPartial(object: Partial<_217.Request>): _217.Request;
            fromAmino(object: _217.RequestAmino): _217.Request;
            toAmino(message: _217.Request): _217.RequestAmino;
            fromAminoMsg(object: _217.RequestAminoMsg): _217.Request;
            fromProtoMsg(message: _217.RequestProtoMsg): _217.Request;
            toProto(message: _217.Request): Uint8Array;
            toProtoMsg(message: _217.Request): _217.RequestProtoMsg;
        };
        RequestEcho: {
            typeUrl: string;
            encode(message: _217.RequestEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.RequestEcho;
            fromPartial(object: Partial<_217.RequestEcho>): _217.RequestEcho;
            fromAmino(object: _217.RequestEchoAmino): _217.RequestEcho;
            toAmino(message: _217.RequestEcho): _217.RequestEchoAmino;
            fromAminoMsg(object: _217.RequestEchoAminoMsg): _217.RequestEcho;
            fromProtoMsg(message: _217.RequestEchoProtoMsg): _217.RequestEcho;
            toProto(message: _217.RequestEcho): Uint8Array;
            toProtoMsg(message: _217.RequestEcho): _217.RequestEchoProtoMsg;
        };
        RequestFlush: {
            typeUrl: string;
            encode(_: _217.RequestFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.RequestFlush;
            fromPartial(_: Partial<_217.RequestFlush>): _217.RequestFlush;
            fromAmino(_: _217.RequestFlushAmino): _217.RequestFlush;
            toAmino(_: _217.RequestFlush): _217.RequestFlushAmino;
            fromAminoMsg(object: _217.RequestFlushAminoMsg): _217.RequestFlush;
            fromProtoMsg(message: _217.RequestFlushProtoMsg): _217.RequestFlush;
            toProto(message: _217.RequestFlush): Uint8Array;
            toProtoMsg(message: _217.RequestFlush): _217.RequestFlushProtoMsg;
        };
        RequestInfo: {
            typeUrl: string;
            encode(message: _217.RequestInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.RequestInfo;
            fromPartial(object: Partial<_217.RequestInfo>): _217.RequestInfo;
            fromAmino(object: _217.RequestInfoAmino): _217.RequestInfo;
            toAmino(message: _217.RequestInfo): _217.RequestInfoAmino;
            fromAminoMsg(object: _217.RequestInfoAminoMsg): _217.RequestInfo;
            fromProtoMsg(message: _217.RequestInfoProtoMsg): _217.RequestInfo;
            toProto(message: _217.RequestInfo): Uint8Array;
            toProtoMsg(message: _217.RequestInfo): _217.RequestInfoProtoMsg;
        };
        RequestInitChain: {
            typeUrl: string;
            encode(message: _217.RequestInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.RequestInitChain;
            fromPartial(object: Partial<_217.RequestInitChain>): _217.RequestInitChain;
            fromAmino(object: _217.RequestInitChainAmino): _217.RequestInitChain;
            toAmino(message: _217.RequestInitChain): _217.RequestInitChainAmino;
            fromAminoMsg(object: _217.RequestInitChainAminoMsg): _217.RequestInitChain;
            fromProtoMsg(message: _217.RequestInitChainProtoMsg): _217.RequestInitChain;
            toProto(message: _217.RequestInitChain): Uint8Array;
            toProtoMsg(message: _217.RequestInitChain): _217.RequestInitChainProtoMsg;
        };
        RequestQuery: {
            typeUrl: string;
            encode(message: _217.RequestQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.RequestQuery;
            fromPartial(object: Partial<_217.RequestQuery>): _217.RequestQuery;
            fromAmino(object: _217.RequestQueryAmino): _217.RequestQuery;
            toAmino(message: _217.RequestQuery): _217.RequestQueryAmino;
            fromAminoMsg(object: _217.RequestQueryAminoMsg): _217.RequestQuery;
            fromProtoMsg(message: _217.RequestQueryProtoMsg): _217.RequestQuery;
            toProto(message: _217.RequestQuery): Uint8Array;
            toProtoMsg(message: _217.RequestQuery): _217.RequestQueryProtoMsg;
        };
        RequestCheckTx: {
            typeUrl: string;
            encode(message: _217.RequestCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.RequestCheckTx;
            fromPartial(object: Partial<_217.RequestCheckTx>): _217.RequestCheckTx;
            fromAmino(object: _217.RequestCheckTxAmino): _217.RequestCheckTx;
            toAmino(message: _217.RequestCheckTx): _217.RequestCheckTxAmino;
            fromAminoMsg(object: _217.RequestCheckTxAminoMsg): _217.RequestCheckTx;
            fromProtoMsg(message: _217.RequestCheckTxProtoMsg): _217.RequestCheckTx;
            toProto(message: _217.RequestCheckTx): Uint8Array;
            toProtoMsg(message: _217.RequestCheckTx): _217.RequestCheckTxProtoMsg;
        };
        RequestCommit: {
            typeUrl: string;
            encode(_: _217.RequestCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.RequestCommit;
            fromPartial(_: Partial<_217.RequestCommit>): _217.RequestCommit;
            fromAmino(_: _217.RequestCommitAmino): _217.RequestCommit;
            toAmino(_: _217.RequestCommit): _217.RequestCommitAmino;
            fromAminoMsg(object: _217.RequestCommitAminoMsg): _217.RequestCommit;
            fromProtoMsg(message: _217.RequestCommitProtoMsg): _217.RequestCommit;
            toProto(message: _217.RequestCommit): Uint8Array;
            toProtoMsg(message: _217.RequestCommit): _217.RequestCommitProtoMsg;
        };
        RequestListSnapshots: {
            typeUrl: string;
            encode(_: _217.RequestListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.RequestListSnapshots;
            fromPartial(_: Partial<_217.RequestListSnapshots>): _217.RequestListSnapshots;
            fromAmino(_: _217.RequestListSnapshotsAmino): _217.RequestListSnapshots;
            toAmino(_: _217.RequestListSnapshots): _217.RequestListSnapshotsAmino;
            fromAminoMsg(object: _217.RequestListSnapshotsAminoMsg): _217.RequestListSnapshots;
            fromProtoMsg(message: _217.RequestListSnapshotsProtoMsg): _217.RequestListSnapshots;
            toProto(message: _217.RequestListSnapshots): Uint8Array;
            toProtoMsg(message: _217.RequestListSnapshots): _217.RequestListSnapshotsProtoMsg;
        };
        RequestOfferSnapshot: {
            typeUrl: string;
            encode(message: _217.RequestOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.RequestOfferSnapshot;
            fromPartial(object: Partial<_217.RequestOfferSnapshot>): _217.RequestOfferSnapshot;
            fromAmino(object: _217.RequestOfferSnapshotAmino): _217.RequestOfferSnapshot;
            toAmino(message: _217.RequestOfferSnapshot): _217.RequestOfferSnapshotAmino;
            fromAminoMsg(object: _217.RequestOfferSnapshotAminoMsg): _217.RequestOfferSnapshot;
            fromProtoMsg(message: _217.RequestOfferSnapshotProtoMsg): _217.RequestOfferSnapshot;
            toProto(message: _217.RequestOfferSnapshot): Uint8Array;
            toProtoMsg(message: _217.RequestOfferSnapshot): _217.RequestOfferSnapshotProtoMsg;
        };
        RequestLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _217.RequestLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.RequestLoadSnapshotChunk;
            fromPartial(object: Partial<_217.RequestLoadSnapshotChunk>): _217.RequestLoadSnapshotChunk;
            fromAmino(object: _217.RequestLoadSnapshotChunkAmino): _217.RequestLoadSnapshotChunk;
            toAmino(message: _217.RequestLoadSnapshotChunk): _217.RequestLoadSnapshotChunkAmino;
            fromAminoMsg(object: _217.RequestLoadSnapshotChunkAminoMsg): _217.RequestLoadSnapshotChunk;
            fromProtoMsg(message: _217.RequestLoadSnapshotChunkProtoMsg): _217.RequestLoadSnapshotChunk;
            toProto(message: _217.RequestLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _217.RequestLoadSnapshotChunk): _217.RequestLoadSnapshotChunkProtoMsg;
        };
        RequestApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _217.RequestApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.RequestApplySnapshotChunk;
            fromPartial(object: Partial<_217.RequestApplySnapshotChunk>): _217.RequestApplySnapshotChunk;
            fromAmino(object: _217.RequestApplySnapshotChunkAmino): _217.RequestApplySnapshotChunk;
            toAmino(message: _217.RequestApplySnapshotChunk): _217.RequestApplySnapshotChunkAmino;
            fromAminoMsg(object: _217.RequestApplySnapshotChunkAminoMsg): _217.RequestApplySnapshotChunk;
            fromProtoMsg(message: _217.RequestApplySnapshotChunkProtoMsg): _217.RequestApplySnapshotChunk;
            toProto(message: _217.RequestApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _217.RequestApplySnapshotChunk): _217.RequestApplySnapshotChunkProtoMsg;
        };
        RequestPrepareProposal: {
            typeUrl: string;
            encode(message: _217.RequestPrepareProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.RequestPrepareProposal;
            fromPartial(object: Partial<_217.RequestPrepareProposal>): _217.RequestPrepareProposal;
            fromAmino(object: _217.RequestPrepareProposalAmino): _217.RequestPrepareProposal;
            toAmino(message: _217.RequestPrepareProposal): _217.RequestPrepareProposalAmino;
            fromAminoMsg(object: _217.RequestPrepareProposalAminoMsg): _217.RequestPrepareProposal;
            fromProtoMsg(message: _217.RequestPrepareProposalProtoMsg): _217.RequestPrepareProposal;
            toProto(message: _217.RequestPrepareProposal): Uint8Array;
            toProtoMsg(message: _217.RequestPrepareProposal): _217.RequestPrepareProposalProtoMsg;
        };
        RequestProcessProposal: {
            typeUrl: string;
            encode(message: _217.RequestProcessProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.RequestProcessProposal;
            fromPartial(object: Partial<_217.RequestProcessProposal>): _217.RequestProcessProposal;
            fromAmino(object: _217.RequestProcessProposalAmino): _217.RequestProcessProposal;
            toAmino(message: _217.RequestProcessProposal): _217.RequestProcessProposalAmino;
            fromAminoMsg(object: _217.RequestProcessProposalAminoMsg): _217.RequestProcessProposal;
            fromProtoMsg(message: _217.RequestProcessProposalProtoMsg): _217.RequestProcessProposal;
            toProto(message: _217.RequestProcessProposal): Uint8Array;
            toProtoMsg(message: _217.RequestProcessProposal): _217.RequestProcessProposalProtoMsg;
        };
        RequestExtendVote: {
            typeUrl: string;
            encode(message: _217.RequestExtendVote, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.RequestExtendVote;
            fromPartial(object: Partial<_217.RequestExtendVote>): _217.RequestExtendVote;
            fromAmino(object: _217.RequestExtendVoteAmino): _217.RequestExtendVote;
            toAmino(message: _217.RequestExtendVote): _217.RequestExtendVoteAmino;
            fromAminoMsg(object: _217.RequestExtendVoteAminoMsg): _217.RequestExtendVote;
            fromProtoMsg(message: _217.RequestExtendVoteProtoMsg): _217.RequestExtendVote;
            toProto(message: _217.RequestExtendVote): Uint8Array;
            toProtoMsg(message: _217.RequestExtendVote): _217.RequestExtendVoteProtoMsg;
        };
        RequestVerifyVoteExtension: {
            typeUrl: string;
            encode(message: _217.RequestVerifyVoteExtension, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.RequestVerifyVoteExtension;
            fromPartial(object: Partial<_217.RequestVerifyVoteExtension>): _217.RequestVerifyVoteExtension;
            fromAmino(object: _217.RequestVerifyVoteExtensionAmino): _217.RequestVerifyVoteExtension;
            toAmino(message: _217.RequestVerifyVoteExtension): _217.RequestVerifyVoteExtensionAmino;
            fromAminoMsg(object: _217.RequestVerifyVoteExtensionAminoMsg): _217.RequestVerifyVoteExtension;
            fromProtoMsg(message: _217.RequestVerifyVoteExtensionProtoMsg): _217.RequestVerifyVoteExtension;
            toProto(message: _217.RequestVerifyVoteExtension): Uint8Array;
            toProtoMsg(message: _217.RequestVerifyVoteExtension): _217.RequestVerifyVoteExtensionProtoMsg;
        };
        RequestFinalizeBlock: {
            typeUrl: string;
            encode(message: _217.RequestFinalizeBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.RequestFinalizeBlock;
            fromPartial(object: Partial<_217.RequestFinalizeBlock>): _217.RequestFinalizeBlock;
            fromAmino(object: _217.RequestFinalizeBlockAmino): _217.RequestFinalizeBlock;
            toAmino(message: _217.RequestFinalizeBlock): _217.RequestFinalizeBlockAmino;
            fromAminoMsg(object: _217.RequestFinalizeBlockAminoMsg): _217.RequestFinalizeBlock;
            fromProtoMsg(message: _217.RequestFinalizeBlockProtoMsg): _217.RequestFinalizeBlock;
            toProto(message: _217.RequestFinalizeBlock): Uint8Array;
            toProtoMsg(message: _217.RequestFinalizeBlock): _217.RequestFinalizeBlockProtoMsg;
        };
        Response: {
            typeUrl: string;
            encode(message: _217.Response, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.Response;
            fromPartial(object: Partial<_217.Response>): _217.Response;
            fromAmino(object: _217.ResponseAmino): _217.Response;
            toAmino(message: _217.Response): _217.ResponseAmino;
            fromAminoMsg(object: _217.ResponseAminoMsg): _217.Response;
            fromProtoMsg(message: _217.ResponseProtoMsg): _217.Response;
            toProto(message: _217.Response): Uint8Array;
            toProtoMsg(message: _217.Response): _217.ResponseProtoMsg;
        };
        ResponseException: {
            typeUrl: string;
            encode(message: _217.ResponseException, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.ResponseException;
            fromPartial(object: Partial<_217.ResponseException>): _217.ResponseException;
            fromAmino(object: _217.ResponseExceptionAmino): _217.ResponseException;
            toAmino(message: _217.ResponseException): _217.ResponseExceptionAmino;
            fromAminoMsg(object: _217.ResponseExceptionAminoMsg): _217.ResponseException;
            fromProtoMsg(message: _217.ResponseExceptionProtoMsg): _217.ResponseException;
            toProto(message: _217.ResponseException): Uint8Array;
            toProtoMsg(message: _217.ResponseException): _217.ResponseExceptionProtoMsg;
        };
        ResponseEcho: {
            typeUrl: string;
            encode(message: _217.ResponseEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.ResponseEcho;
            fromPartial(object: Partial<_217.ResponseEcho>): _217.ResponseEcho;
            fromAmino(object: _217.ResponseEchoAmino): _217.ResponseEcho;
            toAmino(message: _217.ResponseEcho): _217.ResponseEchoAmino;
            fromAminoMsg(object: _217.ResponseEchoAminoMsg): _217.ResponseEcho;
            fromProtoMsg(message: _217.ResponseEchoProtoMsg): _217.ResponseEcho;
            toProto(message: _217.ResponseEcho): Uint8Array;
            toProtoMsg(message: _217.ResponseEcho): _217.ResponseEchoProtoMsg;
        };
        ResponseFlush: {
            typeUrl: string;
            encode(_: _217.ResponseFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.ResponseFlush;
            fromPartial(_: Partial<_217.ResponseFlush>): _217.ResponseFlush;
            fromAmino(_: _217.ResponseFlushAmino): _217.ResponseFlush;
            toAmino(_: _217.ResponseFlush): _217.ResponseFlushAmino;
            fromAminoMsg(object: _217.ResponseFlushAminoMsg): _217.ResponseFlush;
            fromProtoMsg(message: _217.ResponseFlushProtoMsg): _217.ResponseFlush;
            toProto(message: _217.ResponseFlush): Uint8Array;
            toProtoMsg(message: _217.ResponseFlush): _217.ResponseFlushProtoMsg;
        };
        ResponseInfo: {
            typeUrl: string;
            encode(message: _217.ResponseInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.ResponseInfo;
            fromPartial(object: Partial<_217.ResponseInfo>): _217.ResponseInfo;
            fromAmino(object: _217.ResponseInfoAmino): _217.ResponseInfo;
            toAmino(message: _217.ResponseInfo): _217.ResponseInfoAmino;
            fromAminoMsg(object: _217.ResponseInfoAminoMsg): _217.ResponseInfo;
            fromProtoMsg(message: _217.ResponseInfoProtoMsg): _217.ResponseInfo;
            toProto(message: _217.ResponseInfo): Uint8Array;
            toProtoMsg(message: _217.ResponseInfo): _217.ResponseInfoProtoMsg;
        };
        ResponseInitChain: {
            typeUrl: string;
            encode(message: _217.ResponseInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.ResponseInitChain;
            fromPartial(object: Partial<_217.ResponseInitChain>): _217.ResponseInitChain;
            fromAmino(object: _217.ResponseInitChainAmino): _217.ResponseInitChain;
            toAmino(message: _217.ResponseInitChain): _217.ResponseInitChainAmino;
            fromAminoMsg(object: _217.ResponseInitChainAminoMsg): _217.ResponseInitChain;
            fromProtoMsg(message: _217.ResponseInitChainProtoMsg): _217.ResponseInitChain;
            toProto(message: _217.ResponseInitChain): Uint8Array;
            toProtoMsg(message: _217.ResponseInitChain): _217.ResponseInitChainProtoMsg;
        };
        ResponseQuery: {
            typeUrl: string;
            encode(message: _217.ResponseQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.ResponseQuery;
            fromPartial(object: Partial<_217.ResponseQuery>): _217.ResponseQuery;
            fromAmino(object: _217.ResponseQueryAmino): _217.ResponseQuery;
            toAmino(message: _217.ResponseQuery): _217.ResponseQueryAmino;
            fromAminoMsg(object: _217.ResponseQueryAminoMsg): _217.ResponseQuery;
            fromProtoMsg(message: _217.ResponseQueryProtoMsg): _217.ResponseQuery;
            toProto(message: _217.ResponseQuery): Uint8Array;
            toProtoMsg(message: _217.ResponseQuery): _217.ResponseQueryProtoMsg;
        };
        ResponseCheckTx: {
            typeUrl: string;
            encode(message: _217.ResponseCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.ResponseCheckTx;
            fromPartial(object: Partial<_217.ResponseCheckTx>): _217.ResponseCheckTx;
            fromAmino(object: _217.ResponseCheckTxAmino): _217.ResponseCheckTx;
            toAmino(message: _217.ResponseCheckTx): _217.ResponseCheckTxAmino;
            fromAminoMsg(object: _217.ResponseCheckTxAminoMsg): _217.ResponseCheckTx;
            fromProtoMsg(message: _217.ResponseCheckTxProtoMsg): _217.ResponseCheckTx;
            toProto(message: _217.ResponseCheckTx): Uint8Array;
            toProtoMsg(message: _217.ResponseCheckTx): _217.ResponseCheckTxProtoMsg;
        };
        ResponseCommit: {
            typeUrl: string;
            encode(message: _217.ResponseCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.ResponseCommit;
            fromPartial(object: Partial<_217.ResponseCommit>): _217.ResponseCommit;
            fromAmino(object: _217.ResponseCommitAmino): _217.ResponseCommit;
            toAmino(message: _217.ResponseCommit): _217.ResponseCommitAmino;
            fromAminoMsg(object: _217.ResponseCommitAminoMsg): _217.ResponseCommit;
            fromProtoMsg(message: _217.ResponseCommitProtoMsg): _217.ResponseCommit;
            toProto(message: _217.ResponseCommit): Uint8Array;
            toProtoMsg(message: _217.ResponseCommit): _217.ResponseCommitProtoMsg;
        };
        ResponseListSnapshots: {
            typeUrl: string;
            encode(message: _217.ResponseListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.ResponseListSnapshots;
            fromPartial(object: Partial<_217.ResponseListSnapshots>): _217.ResponseListSnapshots;
            fromAmino(object: _217.ResponseListSnapshotsAmino): _217.ResponseListSnapshots;
            toAmino(message: _217.ResponseListSnapshots): _217.ResponseListSnapshotsAmino;
            fromAminoMsg(object: _217.ResponseListSnapshotsAminoMsg): _217.ResponseListSnapshots;
            fromProtoMsg(message: _217.ResponseListSnapshotsProtoMsg): _217.ResponseListSnapshots;
            toProto(message: _217.ResponseListSnapshots): Uint8Array;
            toProtoMsg(message: _217.ResponseListSnapshots): _217.ResponseListSnapshotsProtoMsg;
        };
        ResponseOfferSnapshot: {
            typeUrl: string;
            encode(message: _217.ResponseOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.ResponseOfferSnapshot;
            fromPartial(object: Partial<_217.ResponseOfferSnapshot>): _217.ResponseOfferSnapshot;
            fromAmino(object: _217.ResponseOfferSnapshotAmino): _217.ResponseOfferSnapshot;
            toAmino(message: _217.ResponseOfferSnapshot): _217.ResponseOfferSnapshotAmino;
            fromAminoMsg(object: _217.ResponseOfferSnapshotAminoMsg): _217.ResponseOfferSnapshot;
            fromProtoMsg(message: _217.ResponseOfferSnapshotProtoMsg): _217.ResponseOfferSnapshot;
            toProto(message: _217.ResponseOfferSnapshot): Uint8Array;
            toProtoMsg(message: _217.ResponseOfferSnapshot): _217.ResponseOfferSnapshotProtoMsg;
        };
        ResponseLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _217.ResponseLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.ResponseLoadSnapshotChunk;
            fromPartial(object: Partial<_217.ResponseLoadSnapshotChunk>): _217.ResponseLoadSnapshotChunk;
            fromAmino(object: _217.ResponseLoadSnapshotChunkAmino): _217.ResponseLoadSnapshotChunk;
            toAmino(message: _217.ResponseLoadSnapshotChunk): _217.ResponseLoadSnapshotChunkAmino;
            fromAminoMsg(object: _217.ResponseLoadSnapshotChunkAminoMsg): _217.ResponseLoadSnapshotChunk;
            fromProtoMsg(message: _217.ResponseLoadSnapshotChunkProtoMsg): _217.ResponseLoadSnapshotChunk;
            toProto(message: _217.ResponseLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _217.ResponseLoadSnapshotChunk): _217.ResponseLoadSnapshotChunkProtoMsg;
        };
        ResponseApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _217.ResponseApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.ResponseApplySnapshotChunk;
            fromPartial(object: Partial<_217.ResponseApplySnapshotChunk>): _217.ResponseApplySnapshotChunk;
            fromAmino(object: _217.ResponseApplySnapshotChunkAmino): _217.ResponseApplySnapshotChunk;
            toAmino(message: _217.ResponseApplySnapshotChunk): _217.ResponseApplySnapshotChunkAmino;
            fromAminoMsg(object: _217.ResponseApplySnapshotChunkAminoMsg): _217.ResponseApplySnapshotChunk;
            fromProtoMsg(message: _217.ResponseApplySnapshotChunkProtoMsg): _217.ResponseApplySnapshotChunk;
            toProto(message: _217.ResponseApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _217.ResponseApplySnapshotChunk): _217.ResponseApplySnapshotChunkProtoMsg;
        };
        ResponsePrepareProposal: {
            typeUrl: string;
            encode(message: _217.ResponsePrepareProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.ResponsePrepareProposal;
            fromPartial(object: Partial<_217.ResponsePrepareProposal>): _217.ResponsePrepareProposal;
            fromAmino(object: _217.ResponsePrepareProposalAmino): _217.ResponsePrepareProposal;
            toAmino(message: _217.ResponsePrepareProposal): _217.ResponsePrepareProposalAmino;
            fromAminoMsg(object: _217.ResponsePrepareProposalAminoMsg): _217.ResponsePrepareProposal;
            fromProtoMsg(message: _217.ResponsePrepareProposalProtoMsg): _217.ResponsePrepareProposal;
            toProto(message: _217.ResponsePrepareProposal): Uint8Array;
            toProtoMsg(message: _217.ResponsePrepareProposal): _217.ResponsePrepareProposalProtoMsg;
        };
        ResponseProcessProposal: {
            typeUrl: string;
            encode(message: _217.ResponseProcessProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.ResponseProcessProposal;
            fromPartial(object: Partial<_217.ResponseProcessProposal>): _217.ResponseProcessProposal;
            fromAmino(object: _217.ResponseProcessProposalAmino): _217.ResponseProcessProposal;
            toAmino(message: _217.ResponseProcessProposal): _217.ResponseProcessProposalAmino;
            fromAminoMsg(object: _217.ResponseProcessProposalAminoMsg): _217.ResponseProcessProposal;
            fromProtoMsg(message: _217.ResponseProcessProposalProtoMsg): _217.ResponseProcessProposal;
            toProto(message: _217.ResponseProcessProposal): Uint8Array;
            toProtoMsg(message: _217.ResponseProcessProposal): _217.ResponseProcessProposalProtoMsg;
        };
        ResponseExtendVote: {
            typeUrl: string;
            encode(message: _217.ResponseExtendVote, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.ResponseExtendVote;
            fromPartial(object: Partial<_217.ResponseExtendVote>): _217.ResponseExtendVote;
            fromAmino(object: _217.ResponseExtendVoteAmino): _217.ResponseExtendVote;
            toAmino(message: _217.ResponseExtendVote): _217.ResponseExtendVoteAmino;
            fromAminoMsg(object: _217.ResponseExtendVoteAminoMsg): _217.ResponseExtendVote;
            fromProtoMsg(message: _217.ResponseExtendVoteProtoMsg): _217.ResponseExtendVote;
            toProto(message: _217.ResponseExtendVote): Uint8Array;
            toProtoMsg(message: _217.ResponseExtendVote): _217.ResponseExtendVoteProtoMsg;
        };
        ResponseVerifyVoteExtension: {
            typeUrl: string;
            encode(message: _217.ResponseVerifyVoteExtension, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.ResponseVerifyVoteExtension;
            fromPartial(object: Partial<_217.ResponseVerifyVoteExtension>): _217.ResponseVerifyVoteExtension;
            fromAmino(object: _217.ResponseVerifyVoteExtensionAmino): _217.ResponseVerifyVoteExtension;
            toAmino(message: _217.ResponseVerifyVoteExtension): _217.ResponseVerifyVoteExtensionAmino;
            fromAminoMsg(object: _217.ResponseVerifyVoteExtensionAminoMsg): _217.ResponseVerifyVoteExtension;
            fromProtoMsg(message: _217.ResponseVerifyVoteExtensionProtoMsg): _217.ResponseVerifyVoteExtension;
            toProto(message: _217.ResponseVerifyVoteExtension): Uint8Array;
            toProtoMsg(message: _217.ResponseVerifyVoteExtension): _217.ResponseVerifyVoteExtensionProtoMsg;
        };
        ResponseFinalizeBlock: {
            typeUrl: string;
            encode(message: _217.ResponseFinalizeBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.ResponseFinalizeBlock;
            fromPartial(object: Partial<_217.ResponseFinalizeBlock>): _217.ResponseFinalizeBlock;
            fromAmino(object: _217.ResponseFinalizeBlockAmino): _217.ResponseFinalizeBlock;
            toAmino(message: _217.ResponseFinalizeBlock): _217.ResponseFinalizeBlockAmino;
            fromAminoMsg(object: _217.ResponseFinalizeBlockAminoMsg): _217.ResponseFinalizeBlock;
            fromProtoMsg(message: _217.ResponseFinalizeBlockProtoMsg): _217.ResponseFinalizeBlock;
            toProto(message: _217.ResponseFinalizeBlock): Uint8Array;
            toProtoMsg(message: _217.ResponseFinalizeBlock): _217.ResponseFinalizeBlockProtoMsg;
        };
        CommitInfo: {
            typeUrl: string;
            encode(message: _217.CommitInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.CommitInfo;
            fromPartial(object: Partial<_217.CommitInfo>): _217.CommitInfo;
            fromAmino(object: _217.CommitInfoAmino): _217.CommitInfo;
            toAmino(message: _217.CommitInfo): _217.CommitInfoAmino;
            fromAminoMsg(object: _217.CommitInfoAminoMsg): _217.CommitInfo;
            fromProtoMsg(message: _217.CommitInfoProtoMsg): _217.CommitInfo;
            toProto(message: _217.CommitInfo): Uint8Array;
            toProtoMsg(message: _217.CommitInfo): _217.CommitInfoProtoMsg;
        };
        ExtendedCommitInfo: {
            typeUrl: string;
            encode(message: _217.ExtendedCommitInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.ExtendedCommitInfo;
            fromPartial(object: Partial<_217.ExtendedCommitInfo>): _217.ExtendedCommitInfo;
            fromAmino(object: _217.ExtendedCommitInfoAmino): _217.ExtendedCommitInfo;
            toAmino(message: _217.ExtendedCommitInfo): _217.ExtendedCommitInfoAmino;
            fromAminoMsg(object: _217.ExtendedCommitInfoAminoMsg): _217.ExtendedCommitInfo;
            fromProtoMsg(message: _217.ExtendedCommitInfoProtoMsg): _217.ExtendedCommitInfo;
            toProto(message: _217.ExtendedCommitInfo): Uint8Array;
            toProtoMsg(message: _217.ExtendedCommitInfo): _217.ExtendedCommitInfoProtoMsg;
        };
        Event: {
            typeUrl: string;
            encode(message: _217.Event, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.Event;
            fromPartial(object: Partial<_217.Event>): _217.Event;
            fromAmino(object: _217.EventAmino): _217.Event;
            toAmino(message: _217.Event): _217.EventAmino;
            fromAminoMsg(object: _217.EventAminoMsg): _217.Event;
            fromProtoMsg(message: _217.EventProtoMsg): _217.Event;
            toProto(message: _217.Event): Uint8Array;
            toProtoMsg(message: _217.Event): _217.EventProtoMsg;
        };
        EventAttribute: {
            typeUrl: string;
            encode(message: _217.EventAttribute, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.EventAttribute;
            fromPartial(object: Partial<_217.EventAttribute>): _217.EventAttribute;
            fromAmino(object: _217.EventAttributeAmino): _217.EventAttribute;
            toAmino(message: _217.EventAttribute): _217.EventAttributeAmino;
            fromAminoMsg(object: _217.EventAttributeAminoMsg): _217.EventAttribute;
            fromProtoMsg(message: _217.EventAttributeProtoMsg): _217.EventAttribute;
            toProto(message: _217.EventAttribute): Uint8Array;
            toProtoMsg(message: _217.EventAttribute): _217.EventAttributeProtoMsg;
        };
        ExecTxResult: {
            typeUrl: string;
            encode(message: _217.ExecTxResult, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.ExecTxResult;
            fromPartial(object: Partial<_217.ExecTxResult>): _217.ExecTxResult;
            fromAmino(object: _217.ExecTxResultAmino): _217.ExecTxResult;
            toAmino(message: _217.ExecTxResult): _217.ExecTxResultAmino;
            fromAminoMsg(object: _217.ExecTxResultAminoMsg): _217.ExecTxResult;
            fromProtoMsg(message: _217.ExecTxResultProtoMsg): _217.ExecTxResult;
            toProto(message: _217.ExecTxResult): Uint8Array;
            toProtoMsg(message: _217.ExecTxResult): _217.ExecTxResultProtoMsg;
        };
        TxResult: {
            typeUrl: string;
            encode(message: _217.TxResult, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.TxResult;
            fromPartial(object: Partial<_217.TxResult>): _217.TxResult;
            fromAmino(object: _217.TxResultAmino): _217.TxResult;
            toAmino(message: _217.TxResult): _217.TxResultAmino;
            fromAminoMsg(object: _217.TxResultAminoMsg): _217.TxResult;
            fromProtoMsg(message: _217.TxResultProtoMsg): _217.TxResult;
            toProto(message: _217.TxResult): Uint8Array;
            toProtoMsg(message: _217.TxResult): _217.TxResultProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _217.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.Validator;
            fromPartial(object: Partial<_217.Validator>): _217.Validator;
            fromAmino(object: _217.ValidatorAmino): _217.Validator;
            toAmino(message: _217.Validator): _217.ValidatorAmino;
            fromAminoMsg(object: _217.ValidatorAminoMsg): _217.Validator;
            fromProtoMsg(message: _217.ValidatorProtoMsg): _217.Validator;
            toProto(message: _217.Validator): Uint8Array;
            toProtoMsg(message: _217.Validator): _217.ValidatorProtoMsg;
        };
        ValidatorUpdate: {
            typeUrl: string;
            encode(message: _217.ValidatorUpdate, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.ValidatorUpdate;
            fromPartial(object: Partial<_217.ValidatorUpdate>): _217.ValidatorUpdate;
            fromAmino(object: _217.ValidatorUpdateAmino): _217.ValidatorUpdate;
            toAmino(message: _217.ValidatorUpdate): _217.ValidatorUpdateAmino;
            fromAminoMsg(object: _217.ValidatorUpdateAminoMsg): _217.ValidatorUpdate;
            fromProtoMsg(message: _217.ValidatorUpdateProtoMsg): _217.ValidatorUpdate;
            toProto(message: _217.ValidatorUpdate): Uint8Array;
            toProtoMsg(message: _217.ValidatorUpdate): _217.ValidatorUpdateProtoMsg;
        };
        VoteInfo: {
            typeUrl: string;
            encode(message: _217.VoteInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.VoteInfo;
            fromPartial(object: Partial<_217.VoteInfo>): _217.VoteInfo;
            fromAmino(object: _217.VoteInfoAmino): _217.VoteInfo;
            toAmino(message: _217.VoteInfo): _217.VoteInfoAmino;
            fromAminoMsg(object: _217.VoteInfoAminoMsg): _217.VoteInfo;
            fromProtoMsg(message: _217.VoteInfoProtoMsg): _217.VoteInfo;
            toProto(message: _217.VoteInfo): Uint8Array;
            toProtoMsg(message: _217.VoteInfo): _217.VoteInfoProtoMsg;
        };
        ExtendedVoteInfo: {
            typeUrl: string;
            encode(message: _217.ExtendedVoteInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.ExtendedVoteInfo;
            fromPartial(object: Partial<_217.ExtendedVoteInfo>): _217.ExtendedVoteInfo;
            fromAmino(object: _217.ExtendedVoteInfoAmino): _217.ExtendedVoteInfo;
            toAmino(message: _217.ExtendedVoteInfo): _217.ExtendedVoteInfoAmino;
            fromAminoMsg(object: _217.ExtendedVoteInfoAminoMsg): _217.ExtendedVoteInfo;
            fromProtoMsg(message: _217.ExtendedVoteInfoProtoMsg): _217.ExtendedVoteInfo;
            toProto(message: _217.ExtendedVoteInfo): Uint8Array;
            toProtoMsg(message: _217.ExtendedVoteInfo): _217.ExtendedVoteInfoProtoMsg;
        };
        Misbehavior: {
            typeUrl: string;
            encode(message: _217.Misbehavior, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.Misbehavior;
            fromPartial(object: Partial<_217.Misbehavior>): _217.Misbehavior;
            fromAmino(object: _217.MisbehaviorAmino): _217.Misbehavior;
            toAmino(message: _217.Misbehavior): _217.MisbehaviorAmino;
            fromAminoMsg(object: _217.MisbehaviorAminoMsg): _217.Misbehavior;
            fromProtoMsg(message: _217.MisbehaviorProtoMsg): _217.Misbehavior;
            toProto(message: _217.Misbehavior): Uint8Array;
            toProtoMsg(message: _217.Misbehavior): _217.MisbehaviorProtoMsg;
        };
        Snapshot: {
            typeUrl: string;
            encode(message: _217.Snapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _217.Snapshot;
            fromPartial(object: Partial<_217.Snapshot>): _217.Snapshot;
            fromAmino(object: _217.SnapshotAmino): _217.Snapshot;
            toAmino(message: _217.Snapshot): _217.SnapshotAmino;
            fromAminoMsg(object: _217.SnapshotAminoMsg): _217.Snapshot;
            fromProtoMsg(message: _217.SnapshotProtoMsg): _217.Snapshot;
            toProto(message: _217.Snapshot): Uint8Array;
            toProtoMsg(message: _217.Snapshot): _217.SnapshotProtoMsg;
        };
    };
    const crypto: {
        Proof: {
            typeUrl: string;
            encode(message: _219.Proof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _219.Proof;
            fromPartial(object: Partial<_219.Proof>): _219.Proof;
            fromAmino(object: _219.ProofAmino): _219.Proof;
            toAmino(message: _219.Proof): _219.ProofAmino;
            fromAminoMsg(object: _219.ProofAminoMsg): _219.Proof;
            fromProtoMsg(message: _219.ProofProtoMsg): _219.Proof;
            toProto(message: _219.Proof): Uint8Array;
            toProtoMsg(message: _219.Proof): _219.ProofProtoMsg;
        };
        ValueOp: {
            typeUrl: string;
            encode(message: _219.ValueOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _219.ValueOp;
            fromPartial(object: Partial<_219.ValueOp>): _219.ValueOp;
            fromAmino(object: _219.ValueOpAmino): _219.ValueOp;
            toAmino(message: _219.ValueOp): _219.ValueOpAmino;
            fromAminoMsg(object: _219.ValueOpAminoMsg): _219.ValueOp;
            fromProtoMsg(message: _219.ValueOpProtoMsg): _219.ValueOp;
            toProto(message: _219.ValueOp): Uint8Array;
            toProtoMsg(message: _219.ValueOp): _219.ValueOpProtoMsg;
        };
        DominoOp: {
            typeUrl: string;
            encode(message: _219.DominoOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _219.DominoOp;
            fromPartial(object: Partial<_219.DominoOp>): _219.DominoOp;
            fromAmino(object: _219.DominoOpAmino): _219.DominoOp;
            toAmino(message: _219.DominoOp): _219.DominoOpAmino;
            fromAminoMsg(object: _219.DominoOpAminoMsg): _219.DominoOp;
            fromProtoMsg(message: _219.DominoOpProtoMsg): _219.DominoOp;
            toProto(message: _219.DominoOp): Uint8Array;
            toProtoMsg(message: _219.DominoOp): _219.DominoOpProtoMsg;
        };
        ProofOp: {
            typeUrl: string;
            encode(message: _219.ProofOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _219.ProofOp;
            fromPartial(object: Partial<_219.ProofOp>): _219.ProofOp;
            fromAmino(object: _219.ProofOpAmino): _219.ProofOp;
            toAmino(message: _219.ProofOp): _219.ProofOpAmino;
            fromAminoMsg(object: _219.ProofOpAminoMsg): _219.ProofOp;
            fromProtoMsg(message: _219.ProofOpProtoMsg): _219.ProofOp;
            toProto(message: _219.ProofOp): Uint8Array;
            toProtoMsg(message: _219.ProofOp): _219.ProofOpProtoMsg;
        };
        ProofOps: {
            typeUrl: string;
            encode(message: _219.ProofOps, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _219.ProofOps;
            fromPartial(object: Partial<_219.ProofOps>): _219.ProofOps;
            fromAmino(object: _219.ProofOpsAmino): _219.ProofOps;
            toAmino(message: _219.ProofOps): _219.ProofOpsAmino;
            fromAminoMsg(object: _219.ProofOpsAminoMsg): _219.ProofOps;
            fromProtoMsg(message: _219.ProofOpsProtoMsg): _219.ProofOps;
            toProto(message: _219.ProofOps): Uint8Array;
            toProtoMsg(message: _219.ProofOps): _219.ProofOpsProtoMsg;
        };
        PublicKey: {
            typeUrl: string;
            encode(message: _218.PublicKey, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _218.PublicKey;
            fromPartial(object: Partial<_218.PublicKey>): _218.PublicKey;
            fromAmino(object: _218.PublicKeyAmino): _218.PublicKey;
            toAmino(message: _218.PublicKey): _218.PublicKeyAmino;
            fromAminoMsg(object: _218.PublicKeyAminoMsg): _218.PublicKey;
            fromProtoMsg(message: _218.PublicKeyProtoMsg): _218.PublicKey;
            toProto(message: _218.PublicKey): Uint8Array;
            toProtoMsg(message: _218.PublicKey): _218.PublicKeyProtoMsg;
        };
    };
    namespace libs {
        const bits: {
            BitArray: {
                typeUrl: string;
                encode(message: _220.BitArray, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
                decode(input: Uint8Array | import("..").BinaryReader, length?: number): _220.BitArray;
                fromPartial(object: Partial<_220.BitArray>): _220.BitArray;
                fromAmino(object: _220.BitArrayAmino): _220.BitArray;
                toAmino(message: _220.BitArray): _220.BitArrayAmino;
                fromAminoMsg(object: _220.BitArrayAminoMsg): _220.BitArray;
                fromProtoMsg(message: _220.BitArrayProtoMsg): _220.BitArray;
                toProto(message: _220.BitArray): Uint8Array;
                toProtoMsg(message: _220.BitArray): _220.BitArrayProtoMsg;
            };
        };
    }
    const p2p: {
        NetAddress: {
            typeUrl: string;
            encode(message: _221.NetAddress, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _221.NetAddress;
            fromPartial(object: Partial<_221.NetAddress>): _221.NetAddress;
            fromAmino(object: _221.NetAddressAmino): _221.NetAddress;
            toAmino(message: _221.NetAddress): _221.NetAddressAmino;
            fromAminoMsg(object: _221.NetAddressAminoMsg): _221.NetAddress;
            fromProtoMsg(message: _221.NetAddressProtoMsg): _221.NetAddress;
            toProto(message: _221.NetAddress): Uint8Array;
            toProtoMsg(message: _221.NetAddress): _221.NetAddressProtoMsg;
        };
        ProtocolVersion: {
            typeUrl: string;
            encode(message: _221.ProtocolVersion, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _221.ProtocolVersion;
            fromPartial(object: Partial<_221.ProtocolVersion>): _221.ProtocolVersion;
            fromAmino(object: _221.ProtocolVersionAmino): _221.ProtocolVersion;
            toAmino(message: _221.ProtocolVersion): _221.ProtocolVersionAmino;
            fromAminoMsg(object: _221.ProtocolVersionAminoMsg): _221.ProtocolVersion;
            fromProtoMsg(message: _221.ProtocolVersionProtoMsg): _221.ProtocolVersion;
            toProto(message: _221.ProtocolVersion): Uint8Array;
            toProtoMsg(message: _221.ProtocolVersion): _221.ProtocolVersionProtoMsg;
        };
        DefaultNodeInfo: {
            typeUrl: string;
            encode(message: _221.DefaultNodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _221.DefaultNodeInfo;
            fromPartial(object: Partial<_221.DefaultNodeInfo>): _221.DefaultNodeInfo;
            fromAmino(object: _221.DefaultNodeInfoAmino): _221.DefaultNodeInfo;
            toAmino(message: _221.DefaultNodeInfo): _221.DefaultNodeInfoAmino;
            fromAminoMsg(object: _221.DefaultNodeInfoAminoMsg): _221.DefaultNodeInfo;
            fromProtoMsg(message: _221.DefaultNodeInfoProtoMsg): _221.DefaultNodeInfo;
            toProto(message: _221.DefaultNodeInfo): Uint8Array;
            toProtoMsg(message: _221.DefaultNodeInfo): _221.DefaultNodeInfoProtoMsg;
        };
        DefaultNodeInfoOther: {
            typeUrl: string;
            encode(message: _221.DefaultNodeInfoOther, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _221.DefaultNodeInfoOther;
            fromPartial(object: Partial<_221.DefaultNodeInfoOther>): _221.DefaultNodeInfoOther;
            fromAmino(object: _221.DefaultNodeInfoOtherAmino): _221.DefaultNodeInfoOther;
            toAmino(message: _221.DefaultNodeInfoOther): _221.DefaultNodeInfoOtherAmino;
            fromAminoMsg(object: _221.DefaultNodeInfoOtherAminoMsg): _221.DefaultNodeInfoOther;
            fromProtoMsg(message: _221.DefaultNodeInfoOtherProtoMsg): _221.DefaultNodeInfoOther;
            toProto(message: _221.DefaultNodeInfoOther): Uint8Array;
            toProtoMsg(message: _221.DefaultNodeInfoOther): _221.DefaultNodeInfoOtherProtoMsg;
        };
    };
    const types: {
        blockIDFlagFromJSON(object: any): _226.BlockIDFlag;
        blockIDFlagToJSON(object: _226.BlockIDFlag): string;
        BlockIDFlag: typeof _226.BlockIDFlag;
        BlockIDFlagSDKType: typeof _226.BlockIDFlag;
        BlockIDFlagAmino: typeof _226.BlockIDFlag;
        ValidatorSet: {
            typeUrl: string;
            encode(message: _226.ValidatorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _226.ValidatorSet;
            fromPartial(object: Partial<_226.ValidatorSet>): _226.ValidatorSet;
            fromAmino(object: _226.ValidatorSetAmino): _226.ValidatorSet;
            toAmino(message: _226.ValidatorSet): _226.ValidatorSetAmino;
            fromAminoMsg(object: _226.ValidatorSetAminoMsg): _226.ValidatorSet;
            fromProtoMsg(message: _226.ValidatorSetProtoMsg): _226.ValidatorSet;
            toProto(message: _226.ValidatorSet): Uint8Array;
            toProtoMsg(message: _226.ValidatorSet): _226.ValidatorSetProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _226.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _226.Validator;
            fromPartial(object: Partial<_226.Validator>): _226.Validator;
            fromAmino(object: _226.ValidatorAmino): _226.Validator;
            toAmino(message: _226.Validator): _226.ValidatorAmino;
            fromAminoMsg(object: _226.ValidatorAminoMsg): _226.Validator;
            fromProtoMsg(message: _226.ValidatorProtoMsg): _226.Validator;
            toProto(message: _226.Validator): Uint8Array;
            toProtoMsg(message: _226.Validator): _226.ValidatorProtoMsg;
        };
        SimpleValidator: {
            typeUrl: string;
            encode(message: _226.SimpleValidator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _226.SimpleValidator;
            fromPartial(object: Partial<_226.SimpleValidator>): _226.SimpleValidator;
            fromAmino(object: _226.SimpleValidatorAmino): _226.SimpleValidator;
            toAmino(message: _226.SimpleValidator): _226.SimpleValidatorAmino;
            fromAminoMsg(object: _226.SimpleValidatorAminoMsg): _226.SimpleValidator;
            fromProtoMsg(message: _226.SimpleValidatorProtoMsg): _226.SimpleValidator;
            toProto(message: _226.SimpleValidator): Uint8Array;
            toProtoMsg(message: _226.SimpleValidator): _226.SimpleValidatorProtoMsg;
        };
        signedMsgTypeFromJSON(object: any): _225.SignedMsgType;
        signedMsgTypeToJSON(object: _225.SignedMsgType): string;
        SignedMsgType: typeof _225.SignedMsgType;
        SignedMsgTypeSDKType: typeof _225.SignedMsgType;
        SignedMsgTypeAmino: typeof _225.SignedMsgType;
        PartSetHeader: {
            typeUrl: string;
            encode(message: _225.PartSetHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _225.PartSetHeader;
            fromPartial(object: Partial<_225.PartSetHeader>): _225.PartSetHeader;
            fromAmino(object: _225.PartSetHeaderAmino): _225.PartSetHeader;
            toAmino(message: _225.PartSetHeader): _225.PartSetHeaderAmino;
            fromAminoMsg(object: _225.PartSetHeaderAminoMsg): _225.PartSetHeader;
            fromProtoMsg(message: _225.PartSetHeaderProtoMsg): _225.PartSetHeader;
            toProto(message: _225.PartSetHeader): Uint8Array;
            toProtoMsg(message: _225.PartSetHeader): _225.PartSetHeaderProtoMsg;
        };
        Part: {
            typeUrl: string;
            encode(message: _225.Part, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _225.Part;
            fromPartial(object: Partial<_225.Part>): _225.Part;
            fromAmino(object: _225.PartAmino): _225.Part;
            toAmino(message: _225.Part): _225.PartAmino;
            fromAminoMsg(object: _225.PartAminoMsg): _225.Part;
            fromProtoMsg(message: _225.PartProtoMsg): _225.Part;
            toProto(message: _225.Part): Uint8Array;
            toProtoMsg(message: _225.Part): _225.PartProtoMsg;
        };
        BlockID: {
            typeUrl: string;
            encode(message: _225.BlockID, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _225.BlockID;
            fromPartial(object: Partial<_225.BlockID>): _225.BlockID;
            fromAmino(object: _225.BlockIDAmino): _225.BlockID;
            toAmino(message: _225.BlockID): _225.BlockIDAmino;
            fromAminoMsg(object: _225.BlockIDAminoMsg): _225.BlockID;
            fromProtoMsg(message: _225.BlockIDProtoMsg): _225.BlockID;
            toProto(message: _225.BlockID): Uint8Array;
            toProtoMsg(message: _225.BlockID): _225.BlockIDProtoMsg;
        };
        Header: {
            typeUrl: string;
            encode(message: _225.Header, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _225.Header;
            fromPartial(object: Partial<_225.Header>): _225.Header;
            fromAmino(object: _225.HeaderAmino): _225.Header;
            toAmino(message: _225.Header): _225.HeaderAmino;
            fromAminoMsg(object: _225.HeaderAminoMsg): _225.Header;
            fromProtoMsg(message: _225.HeaderProtoMsg): _225.Header;
            toProto(message: _225.Header): Uint8Array;
            toProtoMsg(message: _225.Header): _225.HeaderProtoMsg;
        };
        Data: {
            typeUrl: string;
            encode(message: _225.Data, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _225.Data;
            fromPartial(object: Partial<_225.Data>): _225.Data;
            fromAmino(object: _225.DataAmino): _225.Data;
            toAmino(message: _225.Data): _225.DataAmino;
            fromAminoMsg(object: _225.DataAminoMsg): _225.Data;
            fromProtoMsg(message: _225.DataProtoMsg): _225.Data;
            toProto(message: _225.Data): Uint8Array;
            toProtoMsg(message: _225.Data): _225.DataProtoMsg;
        };
        Vote: {
            typeUrl: string;
            encode(message: _225.Vote, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _225.Vote;
            fromPartial(object: Partial<_225.Vote>): _225.Vote;
            fromAmino(object: _225.VoteAmino): _225.Vote;
            toAmino(message: _225.Vote): _225.VoteAmino;
            fromAminoMsg(object: _225.VoteAminoMsg): _225.Vote;
            fromProtoMsg(message: _225.VoteProtoMsg): _225.Vote;
            toProto(message: _225.Vote): Uint8Array;
            toProtoMsg(message: _225.Vote): _225.VoteProtoMsg;
        };
        Commit: {
            typeUrl: string;
            encode(message: _225.Commit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _225.Commit;
            fromPartial(object: Partial<_225.Commit>): _225.Commit;
            fromAmino(object: _225.CommitAmino): _225.Commit;
            toAmino(message: _225.Commit): _225.CommitAmino;
            fromAminoMsg(object: _225.CommitAminoMsg): _225.Commit;
            fromProtoMsg(message: _225.CommitProtoMsg): _225.Commit;
            toProto(message: _225.Commit): Uint8Array;
            toProtoMsg(message: _225.Commit): _225.CommitProtoMsg;
        };
        CommitSig: {
            typeUrl: string;
            encode(message: _225.CommitSig, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _225.CommitSig;
            fromPartial(object: Partial<_225.CommitSig>): _225.CommitSig;
            fromAmino(object: _225.CommitSigAmino): _225.CommitSig;
            toAmino(message: _225.CommitSig): _225.CommitSigAmino;
            fromAminoMsg(object: _225.CommitSigAminoMsg): _225.CommitSig;
            fromProtoMsg(message: _225.CommitSigProtoMsg): _225.CommitSig;
            toProto(message: _225.CommitSig): Uint8Array;
            toProtoMsg(message: _225.CommitSig): _225.CommitSigProtoMsg;
        };
        ExtendedCommit: {
            typeUrl: string;
            encode(message: _225.ExtendedCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _225.ExtendedCommit;
            fromPartial(object: Partial<_225.ExtendedCommit>): _225.ExtendedCommit;
            fromAmino(object: _225.ExtendedCommitAmino): _225.ExtendedCommit;
            toAmino(message: _225.ExtendedCommit): _225.ExtendedCommitAmino;
            fromAminoMsg(object: _225.ExtendedCommitAminoMsg): _225.ExtendedCommit;
            fromProtoMsg(message: _225.ExtendedCommitProtoMsg): _225.ExtendedCommit;
            toProto(message: _225.ExtendedCommit): Uint8Array;
            toProtoMsg(message: _225.ExtendedCommit): _225.ExtendedCommitProtoMsg;
        };
        ExtendedCommitSig: {
            typeUrl: string;
            encode(message: _225.ExtendedCommitSig, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _225.ExtendedCommitSig;
            fromPartial(object: Partial<_225.ExtendedCommitSig>): _225.ExtendedCommitSig;
            fromAmino(object: _225.ExtendedCommitSigAmino): _225.ExtendedCommitSig;
            toAmino(message: _225.ExtendedCommitSig): _225.ExtendedCommitSigAmino;
            fromAminoMsg(object: _225.ExtendedCommitSigAminoMsg): _225.ExtendedCommitSig;
            fromProtoMsg(message: _225.ExtendedCommitSigProtoMsg): _225.ExtendedCommitSig;
            toProto(message: _225.ExtendedCommitSig): Uint8Array;
            toProtoMsg(message: _225.ExtendedCommitSig): _225.ExtendedCommitSigProtoMsg;
        };
        Proposal: {
            typeUrl: string;
            encode(message: _225.Proposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _225.Proposal;
            fromPartial(object: Partial<_225.Proposal>): _225.Proposal;
            fromAmino(object: _225.ProposalAmino): _225.Proposal;
            toAmino(message: _225.Proposal): _225.ProposalAmino;
            fromAminoMsg(object: _225.ProposalAminoMsg): _225.Proposal;
            fromProtoMsg(message: _225.ProposalProtoMsg): _225.Proposal;
            toProto(message: _225.Proposal): Uint8Array;
            toProtoMsg(message: _225.Proposal): _225.ProposalProtoMsg;
        };
        SignedHeader: {
            typeUrl: string;
            encode(message: _225.SignedHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _225.SignedHeader;
            fromPartial(object: Partial<_225.SignedHeader>): _225.SignedHeader;
            fromAmino(object: _225.SignedHeaderAmino): _225.SignedHeader;
            toAmino(message: _225.SignedHeader): _225.SignedHeaderAmino;
            fromAminoMsg(object: _225.SignedHeaderAminoMsg): _225.SignedHeader;
            fromProtoMsg(message: _225.SignedHeaderProtoMsg): _225.SignedHeader;
            toProto(message: _225.SignedHeader): Uint8Array;
            toProtoMsg(message: _225.SignedHeader): _225.SignedHeaderProtoMsg;
        };
        LightBlock: {
            typeUrl: string;
            encode(message: _225.LightBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _225.LightBlock;
            fromPartial(object: Partial<_225.LightBlock>): _225.LightBlock;
            fromAmino(object: _225.LightBlockAmino): _225.LightBlock;
            toAmino(message: _225.LightBlock): _225.LightBlockAmino;
            fromAminoMsg(object: _225.LightBlockAminoMsg): _225.LightBlock;
            fromProtoMsg(message: _225.LightBlockProtoMsg): _225.LightBlock;
            toProto(message: _225.LightBlock): Uint8Array;
            toProtoMsg(message: _225.LightBlock): _225.LightBlockProtoMsg;
        };
        BlockMeta: {
            typeUrl: string;
            encode(message: _225.BlockMeta, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _225.BlockMeta;
            fromPartial(object: Partial<_225.BlockMeta>): _225.BlockMeta;
            fromAmino(object: _225.BlockMetaAmino): _225.BlockMeta;
            toAmino(message: _225.BlockMeta): _225.BlockMetaAmino;
            fromAminoMsg(object: _225.BlockMetaAminoMsg): _225.BlockMeta;
            fromProtoMsg(message: _225.BlockMetaProtoMsg): _225.BlockMeta;
            toProto(message: _225.BlockMeta): Uint8Array;
            toProtoMsg(message: _225.BlockMeta): _225.BlockMetaProtoMsg;
        };
        TxProof: {
            typeUrl: string;
            encode(message: _225.TxProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _225.TxProof;
            fromPartial(object: Partial<_225.TxProof>): _225.TxProof;
            fromAmino(object: _225.TxProofAmino): _225.TxProof;
            toAmino(message: _225.TxProof): _225.TxProofAmino;
            fromAminoMsg(object: _225.TxProofAminoMsg): _225.TxProof;
            fromProtoMsg(message: _225.TxProofProtoMsg): _225.TxProof;
            toProto(message: _225.TxProof): Uint8Array;
            toProtoMsg(message: _225.TxProof): _225.TxProofProtoMsg;
        };
        ConsensusParams: {
            typeUrl: string;
            encode(message: _224.ConsensusParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _224.ConsensusParams;
            fromPartial(object: Partial<_224.ConsensusParams>): _224.ConsensusParams;
            fromAmino(object: _224.ConsensusParamsAmino): _224.ConsensusParams;
            toAmino(message: _224.ConsensusParams): _224.ConsensusParamsAmino;
            fromAminoMsg(object: _224.ConsensusParamsAminoMsg): _224.ConsensusParams;
            fromProtoMsg(message: _224.ConsensusParamsProtoMsg): _224.ConsensusParams;
            toProto(message: _224.ConsensusParams): Uint8Array;
            toProtoMsg(message: _224.ConsensusParams): _224.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            typeUrl: string;
            encode(message: _224.BlockParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _224.BlockParams;
            fromPartial(object: Partial<_224.BlockParams>): _224.BlockParams;
            fromAmino(object: _224.BlockParamsAmino): _224.BlockParams;
            toAmino(message: _224.BlockParams): _224.BlockParamsAmino;
            fromAminoMsg(object: _224.BlockParamsAminoMsg): _224.BlockParams;
            fromProtoMsg(message: _224.BlockParamsProtoMsg): _224.BlockParams;
            toProto(message: _224.BlockParams): Uint8Array;
            toProtoMsg(message: _224.BlockParams): _224.BlockParamsProtoMsg;
        };
        EvidenceParams: {
            typeUrl: string;
            encode(message: _224.EvidenceParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _224.EvidenceParams;
            fromPartial(object: Partial<_224.EvidenceParams>): _224.EvidenceParams;
            fromAmino(object: _224.EvidenceParamsAmino): _224.EvidenceParams;
            toAmino(message: _224.EvidenceParams): _224.EvidenceParamsAmino;
            fromAminoMsg(object: _224.EvidenceParamsAminoMsg): _224.EvidenceParams;
            fromProtoMsg(message: _224.EvidenceParamsProtoMsg): _224.EvidenceParams;
            toProto(message: _224.EvidenceParams): Uint8Array;
            toProtoMsg(message: _224.EvidenceParams): _224.EvidenceParamsProtoMsg;
        };
        ValidatorParams: {
            typeUrl: string;
            encode(message: _224.ValidatorParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _224.ValidatorParams;
            fromPartial(object: Partial<_224.ValidatorParams>): _224.ValidatorParams;
            fromAmino(object: _224.ValidatorParamsAmino): _224.ValidatorParams;
            toAmino(message: _224.ValidatorParams): _224.ValidatorParamsAmino;
            fromAminoMsg(object: _224.ValidatorParamsAminoMsg): _224.ValidatorParams;
            fromProtoMsg(message: _224.ValidatorParamsProtoMsg): _224.ValidatorParams;
            toProto(message: _224.ValidatorParams): Uint8Array;
            toProtoMsg(message: _224.ValidatorParams): _224.ValidatorParamsProtoMsg;
        };
        VersionParams: {
            typeUrl: string;
            encode(message: _224.VersionParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _224.VersionParams;
            fromPartial(object: Partial<_224.VersionParams>): _224.VersionParams;
            fromAmino(object: _224.VersionParamsAmino): _224.VersionParams;
            toAmino(message: _224.VersionParams): _224.VersionParamsAmino;
            fromAminoMsg(object: _224.VersionParamsAminoMsg): _224.VersionParams;
            fromProtoMsg(message: _224.VersionParamsProtoMsg): _224.VersionParams;
            toProto(message: _224.VersionParams): Uint8Array;
            toProtoMsg(message: _224.VersionParams): _224.VersionParamsProtoMsg;
        };
        HashedParams: {
            typeUrl: string;
            encode(message: _224.HashedParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _224.HashedParams;
            fromPartial(object: Partial<_224.HashedParams>): _224.HashedParams;
            fromAmino(object: _224.HashedParamsAmino): _224.HashedParams;
            toAmino(message: _224.HashedParams): _224.HashedParamsAmino;
            fromAminoMsg(object: _224.HashedParamsAminoMsg): _224.HashedParams;
            fromProtoMsg(message: _224.HashedParamsProtoMsg): _224.HashedParams;
            toProto(message: _224.HashedParams): Uint8Array;
            toProtoMsg(message: _224.HashedParams): _224.HashedParamsProtoMsg;
        };
        ABCIParams: {
            typeUrl: string;
            encode(message: _224.ABCIParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _224.ABCIParams;
            fromPartial(object: Partial<_224.ABCIParams>): _224.ABCIParams;
            fromAmino(object: _224.ABCIParamsAmino): _224.ABCIParams;
            toAmino(message: _224.ABCIParams): _224.ABCIParamsAmino;
            fromAminoMsg(object: _224.ABCIParamsAminoMsg): _224.ABCIParams;
            fromProtoMsg(message: _224.ABCIParamsProtoMsg): _224.ABCIParams;
            toProto(message: _224.ABCIParams): Uint8Array;
            toProtoMsg(message: _224.ABCIParams): _224.ABCIParamsProtoMsg;
        };
        Evidence: {
            typeUrl: string;
            encode(message: _223.Evidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _223.Evidence;
            fromPartial(object: Partial<_223.Evidence>): _223.Evidence;
            fromAmino(object: _223.EvidenceAmino): _223.Evidence;
            toAmino(message: _223.Evidence): _223.EvidenceAmino;
            fromAminoMsg(object: _223.EvidenceAminoMsg): _223.Evidence;
            fromProtoMsg(message: _223.EvidenceProtoMsg): _223.Evidence;
            toProto(message: _223.Evidence): Uint8Array;
            toProtoMsg(message: _223.Evidence): _223.EvidenceProtoMsg;
        };
        DuplicateVoteEvidence: {
            typeUrl: string;
            encode(message: _223.DuplicateVoteEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _223.DuplicateVoteEvidence;
            fromPartial(object: Partial<_223.DuplicateVoteEvidence>): _223.DuplicateVoteEvidence;
            fromAmino(object: _223.DuplicateVoteEvidenceAmino): _223.DuplicateVoteEvidence;
            toAmino(message: _223.DuplicateVoteEvidence): _223.DuplicateVoteEvidenceAmino;
            fromAminoMsg(object: _223.DuplicateVoteEvidenceAminoMsg): _223.DuplicateVoteEvidence;
            fromProtoMsg(message: _223.DuplicateVoteEvidenceProtoMsg): _223.DuplicateVoteEvidence;
            toProto(message: _223.DuplicateVoteEvidence): Uint8Array;
            toProtoMsg(message: _223.DuplicateVoteEvidence): _223.DuplicateVoteEvidenceProtoMsg;
        };
        LightClientAttackEvidence: {
            typeUrl: string;
            encode(message: _223.LightClientAttackEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _223.LightClientAttackEvidence;
            fromPartial(object: Partial<_223.LightClientAttackEvidence>): _223.LightClientAttackEvidence;
            fromAmino(object: _223.LightClientAttackEvidenceAmino): _223.LightClientAttackEvidence;
            toAmino(message: _223.LightClientAttackEvidence): _223.LightClientAttackEvidenceAmino;
            fromAminoMsg(object: _223.LightClientAttackEvidenceAminoMsg): _223.LightClientAttackEvidence;
            fromProtoMsg(message: _223.LightClientAttackEvidenceProtoMsg): _223.LightClientAttackEvidence;
            toProto(message: _223.LightClientAttackEvidence): Uint8Array;
            toProtoMsg(message: _223.LightClientAttackEvidence): _223.LightClientAttackEvidenceProtoMsg;
        };
        EvidenceList: {
            typeUrl: string;
            encode(message: _223.EvidenceList, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _223.EvidenceList;
            fromPartial(object: Partial<_223.EvidenceList>): _223.EvidenceList;
            fromAmino(object: _223.EvidenceListAmino): _223.EvidenceList;
            toAmino(message: _223.EvidenceList): _223.EvidenceListAmino;
            fromAminoMsg(object: _223.EvidenceListAminoMsg): _223.EvidenceList;
            fromProtoMsg(message: _223.EvidenceListProtoMsg): _223.EvidenceList;
            toProto(message: _223.EvidenceList): Uint8Array;
            toProtoMsg(message: _223.EvidenceList): _223.EvidenceListProtoMsg;
        };
        Block: {
            typeUrl: string;
            encode(message: _222.Block, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _222.Block;
            fromPartial(object: Partial<_222.Block>): _222.Block;
            fromAmino(object: _222.BlockAmino): _222.Block;
            toAmino(message: _222.Block): _222.BlockAmino;
            fromAminoMsg(object: _222.BlockAminoMsg): _222.Block;
            fromProtoMsg(message: _222.BlockProtoMsg): _222.Block;
            toProto(message: _222.Block): Uint8Array;
            toProtoMsg(message: _222.Block): _222.BlockProtoMsg;
        };
    };
    const version: {
        App: {
            typeUrl: string;
            encode(message: _227.App, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _227.App;
            fromPartial(object: Partial<_227.App>): _227.App;
            fromAmino(object: _227.AppAmino): _227.App;
            toAmino(message: _227.App): _227.AppAmino;
            fromAminoMsg(object: _227.AppAminoMsg): _227.App;
            fromProtoMsg(message: _227.AppProtoMsg): _227.App;
            toProto(message: _227.App): Uint8Array;
            toProtoMsg(message: _227.App): _227.AppProtoMsg;
        };
        Consensus: {
            typeUrl: string;
            encode(message: _227.Consensus, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _227.Consensus;
            fromPartial(object: Partial<_227.Consensus>): _227.Consensus;
            fromAmino(object: _227.ConsensusAmino): _227.Consensus;
            toAmino(message: _227.Consensus): _227.ConsensusAmino;
            fromAminoMsg(object: _227.ConsensusAminoMsg): _227.Consensus;
            fromProtoMsg(message: _227.ConsensusProtoMsg): _227.Consensus;
            toProto(message: _227.Consensus): Uint8Array;
            toProtoMsg(message: _227.Consensus): _227.ConsensusProtoMsg;
        };
    };
}
